import { Applicant } from "./types";

export const terminalScript: string[] = [
  "Loading applicant...",
  "Extracting financial documents...",
  "Running risk model...",
  "Cross-checking employment records...",
  "Verifying income statements...",
  "Calculating debt-to-income ratio...",
  "Flagging employment discrepancy...",
  "Generating credit memo...",
  "Ready for officer review.",
];

export const applicants: Applicant[] = [
  {
    id: "APP-1042",
    name: "Marcus Whitfield",
    avatarInitials: "MW",
    loanAmount: 340000,
    loanPurpose: "Home purchase",
    submittedAt: "2026-07-10T09:14:00Z",
    status: "approved",
    employment: {
      employer: "Northgate Logistics",
      title: "Operations Director",
      yearsEmployed: 6,
      monthlyIncome: 11200,
      verified: true,
    },
    riskScore: {
      score: 18,
      band: "low",
      debtToIncome: 0.24,
      factors: [
        { label: "Stable employment history", weight: -0.4, detail: "6 years at current employer, no gaps." },
        { label: "Low debt-to-income ratio", weight: -0.3, detail: "24% DTI, well under 36% threshold." },
        { label: "Strong liquidity reserve", weight: -0.2, detail: "8.2 months of expenses in reserve." },
        { label: "Loan-to-value ratio", weight: 0.1, detail: "78% LTV, within normal range." },
      ],
    },
    documents: [
      { id: "d1", name: "Pay stub — June 2026", type: "pay_stub", status: "verified", note: "Matches declared income within 1%.", uploadedAt: "2026-07-09" },
      { id: "d2", name: "Bank statement — Q2 2026", type: "bank_statement", status: "verified", note: "Consistent deposit history, no irregular transfers.", uploadedAt: "2026-07-09" },
      { id: "d3", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed against record.", uploadedAt: "2026-07-09" },
      { id: "d4", name: "Employment letter", type: "employment_letter", status: "verified", note: "Title and tenure match employer records.", uploadedAt: "2026-07-09" },
    ],
    creditMemo: {
      summary: "Applicant demonstrates strong repayment capacity with stable, verifiable income and low existing debt obligations. All submitted documentation is internally consistent.",
      strengths: ["6-year tenure at current employer", "24% debt-to-income ratio", "8.2 months liquidity reserve", "No document discrepancies"],
      concerns: ["Loan-to-value ratio slightly above regional average"],
      recommendation: "approve",
      generatedAt: "2026-07-10T09:21:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-10T09:14:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-10T09:14:12Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-10T09:14:40Z", actor: "agent", label: "Extracting financial documents..." },
      { id: "a4", timestamp: "2026-07-10T09:15:55Z", actor: "agent", label: "Running risk model...", detail: "Score computed: 18 / low band" },
      { id: "a5", timestamp: "2026-07-10T09:17:02Z", actor: "agent", label: "Cross-checking employment records...", detail: "Match confirmed with employment letter" },
      { id: "a6", timestamp: "2026-07-10T09:19:30Z", actor: "agent", label: "Verifying income statements...", detail: "Deviation: 1.0%" },
      { id: "a7", timestamp: "2026-07-10T09:20:10Z", actor: "agent", label: "Calculating debt-to-income ratio...", detail: "24% DTI" },
      { id: "a8", timestamp: "2026-07-10T09:21:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a9", timestamp: "2026-07-10T09:21:04Z", actor: "system", label: "Ready for officer review." },
      { id: "a10", timestamp: "2026-07-10T11:02:00Z", actor: "officer", label: "Decision recorded: Approved", detail: "By S. Alaba" },
    ],
    officerDecision: { decidedBy: "S. Alaba", decision: "approved", note: "Clean file, strong ratios. Approved at standard rate.", decidedAt: "2026-07-10T11:02:00Z" },
  },
  {
    id: "APP-1043",
    name: "Renée Castellano",
    avatarInitials: "RC",
    loanAmount: 58000,
    loanPurpose: "Debt consolidation",
    submittedAt: "2026-07-10T13:40:00Z",
    status: "rejected",
    employment: {
      employer: "Fixed-term contractor (self-reported)",
      title: "Freelance consultant",
      yearsEmployed: 1,
      monthlyIncome: 3400,
      verified: false,
    },
    riskScore: {
      score: 82,
      band: "high",
      debtToIncome: 0.61,
      factors: [
        { label: "Unverifiable income source", weight: 0.4, detail: "No employer-issued documentation available." },
        { label: "High debt-to-income ratio", weight: 0.35, detail: "61% DTI, exceeds acceptable threshold." },
        { label: "Short income history", weight: 0.2, detail: "Only 11 months of consistent deposits." },
        { label: "Existing delinquency flag", weight: 0.15, detail: "One 60-day late payment in past 12 months." },
      ],
    },
    documents: [
      { id: "d1", name: "Bank statement — Q2 2026", type: "bank_statement", status: "flagged", note: "Irregular deposit pattern inconsistent with stated income.", uploadedAt: "2026-07-10" },
      { id: "d2", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-10" },
      { id: "d3", name: "Self-reported income statement", type: "pay_stub", status: "flagged", note: "No third-party corroboration available.", uploadedAt: "2026-07-10" },
    ],
    creditMemo: {
      summary: "Applicant's income cannot be independently verified and reported debt obligations substantially exceed sustainable thresholds. Bank statement deposit pattern does not corroborate stated monthly income.",
      strengths: ["No history of default"],
      concerns: ["61% debt-to-income ratio", "Unverifiable self-employment income", "One prior 60-day delinquency", "Deposit irregularities in bank statement"],
      recommendation: "reject",
      generatedAt: "2026-07-10T14:02:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-10T13:40:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-10T13:40:20Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-10T13:41:10Z", actor: "agent", label: "Extracting financial documents..." },
      { id: "a4", timestamp: "2026-07-10T13:43:00Z", actor: "agent", label: "Cross-checking employment records...", detail: "No employer record found" },
      { id: "a5", timestamp: "2026-07-10T13:45:40Z", actor: "agent", label: "Verifying income statements...", detail: "Deposit pattern mismatch flagged" },
      { id: "a6", timestamp: "2026-07-10T13:47:15Z", actor: "agent", label: "Calculating debt-to-income ratio...", detail: "61% DTI" },
      { id: "a7", timestamp: "2026-07-10T13:48:00Z", actor: "agent", label: "Running risk model...", detail: "Score computed: 82 / high band" },
      { id: "a8", timestamp: "2026-07-10T14:02:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a9", timestamp: "2026-07-10T14:02:05Z", actor: "system", label: "Ready for officer review." },
      { id: "a10", timestamp: "2026-07-10T16:20:00Z", actor: "officer", label: "Decision recorded: Rejected", detail: "By D. Kowalski" },
    ],
    officerDecision: { decidedBy: "D. Kowalski", decision: "rejected", note: "DTI and unverifiable income both exceed policy limits.", decidedAt: "2026-07-10T16:20:00Z" },
  },
  {
    id: "APP-1044",
    name: "Tobias Ferreira",
    avatarInitials: "TF",
    loanAmount: 125000,
    loanPurpose: "Business expansion",
    submittedAt: "2026-07-11T08:05:00Z",
    status: "manual_review",
    employment: {
      employer: "Ferreira & Co. (owner)",
      title: "Founder / Managing Partner",
      yearsEmployed: 4,
      monthlyIncome: 9100,
      verified: true,
    },
    riskScore: {
      score: 51,
      band: "medium",
      debtToIncome: 0.38,
      factors: [
        { label: "Business income volatility", weight: 0.3, detail: "Monthly revenue variance of 22% over trailing 12 months." },
        { label: "Adequate collateral offered", weight: -0.2, detail: "Commercial property pledged at 65% LTV." },
        { label: "Debt-to-income marginally elevated", weight: 0.15, detail: "38% DTI, just above the 36% guideline." },
        { label: "Owner-operator tenure", weight: -0.15, detail: "4 years operating the business profitably." },
      ],
    },
    documents: [
      { id: "d1", name: "Tax return — FY2025", type: "tax_return", status: "verified", note: "Filed and matches reported business income.", uploadedAt: "2026-07-11" },
      { id: "d2", name: "Bank statement — Q2 2026", type: "bank_statement", status: "verified", note: "Revenue consistent with tax filings.", uploadedAt: "2026-07-11" },
      { id: "d3", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-11" },
    ],
    creditMemo: {
      summary: "Applicant shows sound business fundamentals with adequate collateral, but revenue volatility and a borderline debt-to-income ratio place this file outside automatic-approval thresholds. Recommend officer review of trailing revenue trend.",
      strengths: ["4 years profitable operation", "Collateral pledged at 65% LTV", "Verified tax and bank records"],
      concerns: ["22% revenue variance over trailing 12 months", "38% debt-to-income ratio"],
      recommendation: "manual_review",
      generatedAt: "2026-07-11T08:30:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-11T08:05:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-11T08:05:18Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-11T08:06:40Z", actor: "agent", label: "Extracting financial documents..." },
      { id: "a4", timestamp: "2026-07-11T08:10:00Z", actor: "agent", label: "Cross-checking employment records...", detail: "Owner-operator confirmed" },
      { id: "a5", timestamp: "2026-07-11T08:15:20Z", actor: "agent", label: "Verifying income statements...", detail: "Matches tax filings" },
      { id: "a6", timestamp: "2026-07-11T08:20:00Z", actor: "agent", label: "Calculating debt-to-income ratio...", detail: "38% DTI" },
      { id: "a7", timestamp: "2026-07-11T08:25:00Z", actor: "agent", label: "Running risk model...", detail: "Score computed: 51 / medium band" },
      { id: "a8", timestamp: "2026-07-11T08:30:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a9", timestamp: "2026-07-11T08:30:10Z", actor: "system", label: "Flagged for manual review." },
    ],
    officerDecision: { decidedBy: "", decision: "pending", note: "", decidedAt: null },
  },
  {
    id: "APP-1045",
    name: "Priya Anand",
    avatarInitials: "PA",
    loanAmount: 210000,
    loanPurpose: "Home refinance",
    submittedAt: "2026-07-11T10:22:00Z",
    status: "manual_review",
    employment: {
      employer: "Solvent Analytics Inc.",
      title: "Senior Data Engineer",
      yearsEmployed: 3,
      monthlyIncome: 9800,
      verified: false,
    },
    riskScore: {
      score: 46,
      band: "medium",
      debtToIncome: 0.31,
      factors: [
        { label: "Employment discrepancy detected", weight: 0.45, detail: "Employment letter lists 'Data Engineer II', pay stub lists 'Senior Data Engineer'." },
        { label: "Healthy debt-to-income ratio", weight: -0.3, detail: "31% DTI." },
        { label: "Consistent deposit history", weight: -0.2, detail: "12 months of stable payroll deposits." },
        { label: "Verification pending", weight: 0.1, detail: "Employer HR has not confirmed title change." },
      ],
    },
    documents: [
      { id: "d1", name: "Pay stub — June 2026", type: "pay_stub", status: "verified", note: "Income figure matches declared amount.", uploadedAt: "2026-07-11" },
      { id: "d2", name: "Employment letter", type: "employment_letter", status: "flagged", note: "Job title mismatch against pay stub — possible recent promotion not yet reflected in HR records.", uploadedAt: "2026-07-11" },
      { id: "d3", name: "Bank statement — Q2 2026", type: "bank_statement", status: "verified", note: "Deposits align with payroll cycle.", uploadedAt: "2026-07-11" },
      { id: "d4", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-11" },
    ],
    creditMemo: {
      summary: "Financials are otherwise sound, but a title discrepancy between the employment letter and most recent pay stub was flagged during cross-checking and could not be automatically resolved. Recommend confirming with employer HR before proceeding.",
      strengths: ["31% debt-to-income ratio", "12 months of stable deposits", "No adverse credit history"],
      concerns: ["Job title mismatch between employment letter and pay stub", "Employer verification incomplete"],
      recommendation: "manual_review",
      generatedAt: "2026-07-11T10:48:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-11T10:22:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-11T10:22:15Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-11T10:23:30Z", actor: "agent", label: "Extracting financial documents..." },
      { id: "a4", timestamp: "2026-07-11T10:26:00Z", actor: "agent", label: "Cross-checking employment records..." },
      { id: "a5", timestamp: "2026-07-11T10:26:44Z", actor: "agent", label: "Flagging employment discrepancy...", detail: "Title mismatch: 'Data Engineer II' vs 'Senior Data Engineer'" },
      { id: "a6", timestamp: "2026-07-11T10:35:00Z", actor: "agent", label: "Verifying income statements...", detail: "Amounts consistent" },
      { id: "a7", timestamp: "2026-07-11T10:42:00Z", actor: "agent", label: "Calculating debt-to-income ratio...", detail: "31% DTI" },
      { id: "a8", timestamp: "2026-07-11T10:48:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a9", timestamp: "2026-07-11T10:48:06Z", actor: "system", label: "Flagged for manual review." },
    ],
    officerDecision: { decidedBy: "", decision: "pending", note: "", decidedAt: null },
  },
  {
    id: "APP-1046",
    name: "Elena Vasquez",
    avatarInitials: "EV",
    loanAmount: 92000,
    loanPurpose: "Auto loan",
    submittedAt: "2026-07-11T14:00:00Z",
    status: "approved",
    employment: { employer: "Brightline Health Systems", title: "Registered Nurse", yearsEmployed: 5, monthlyIncome: 6700, verified: true },
    riskScore: {
      score: 22,
      band: "low",
      debtToIncome: 0.27,
      factors: [
        { label: "Stable healthcare-sector employment", weight: -0.35, detail: "5 years, essential-sector employer." },
        { label: "Low debt-to-income ratio", weight: -0.3, detail: "27% DTI." },
        { label: "Vehicle as collateral", weight: -0.1, detail: "Loan fully collateralized by vehicle asset." },
      ],
    },
    documents: [
      { id: "d1", name: "Pay stub — June 2026", type: "pay_stub", status: "verified", note: "Matches declared income.", uploadedAt: "2026-07-11" },
      { id: "d2", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-11" },
      { id: "d3", name: "Bank statement — Q2 2026", type: "bank_statement", status: "verified", note: "No irregularities.", uploadedAt: "2026-07-11" },
    ],
    creditMemo: {
      summary: "Strong and straightforward file. Stable essential-sector income, low leverage, and a fully collateralized loan structure.",
      strengths: ["5-year employment tenure", "27% DTI", "Fully collateralized"],
      concerns: [],
      recommendation: "approve",
      generatedAt: "2026-07-11T14:19:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-11T14:00:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-11T14:00:14Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-11T14:08:00Z", actor: "agent", label: "Running risk model...", detail: "Score computed: 22 / low band" },
      { id: "a4", timestamp: "2026-07-11T14:19:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a5", timestamp: "2026-07-11T14:19:05Z", actor: "system", label: "Ready for officer review." },
      { id: "a6", timestamp: "2026-07-11T15:00:00Z", actor: "officer", label: "Decision recorded: Approved", detail: "By S. Alaba" },
    ],
    officerDecision: { decidedBy: "S. Alaba", decision: "approved", note: "Straightforward approval.", decidedAt: "2026-07-11T15:00:00Z" },
  },
  {
    id: "APP-1047",
    name: "Jonas Bekker",
    avatarInitials: "JB",
    loanAmount: 47000,
    loanPurpose: "Personal loan",
    submittedAt: "2026-07-12T09:30:00Z",
    status: "pending",
    employment: { employer: "Redline Freight Co.", title: "Fleet Dispatcher", yearsEmployed: 2, monthlyIncome: 4900, verified: true },
    riskScore: {
      score: 39,
      band: "medium",
      debtToIncome: 0.33,
      factors: [
        { label: "Moderate tenure", weight: 0.1, detail: "2 years at current employer." },
        { label: "Acceptable debt-to-income ratio", weight: -0.2, detail: "33% DTI." },
      ],
    },
    documents: [
      { id: "d1", name: "Pay stub — June 2026", type: "pay_stub", status: "pending", note: "Awaiting agent verification.", uploadedAt: "2026-07-12" },
      { id: "d2", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-12" },
    ],
    creditMemo: {
      summary: "Analysis in progress. Preliminary indicators are within normal range.",
      strengths: ["33% DTI"],
      concerns: ["Document verification incomplete"],
      recommendation: "manual_review",
      generatedAt: "2026-07-12T09:31:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-12T09:30:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-12T09:30:20Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-12T09:31:00Z", actor: "agent", label: "Extracting financial documents..." },
    ],
    officerDecision: { decidedBy: "", decision: "pending", note: "", decidedAt: null },
  },
  {
    id: "APP-1048",
    name: "Aisha Mbeki",
    avatarInitials: "AM",
    loanAmount: 275000,
    loanPurpose: "Home purchase",
    submittedAt: "2026-07-12T11:15:00Z",
    status: "approved",
    employment: { employer: "Meridian Public Schools", title: "District Administrator", yearsEmployed: 9, monthlyIncome: 8300, verified: true },
    riskScore: {
      score: 15,
      band: "low",
      debtToIncome: 0.21,
      factors: [
        { label: "Long-tenured public-sector role", weight: -0.4, detail: "9 years, stable government employer." },
        { label: "Low debt-to-income ratio", weight: -0.3, detail: "21% DTI." },
        { label: "Excellent payment history", weight: -0.2, detail: "No missed payments in credit history reviewed." },
      ],
    },
    documents: [
      { id: "d1", name: "Pay stub — June 2026", type: "pay_stub", status: "verified", note: "Matches declared income.", uploadedAt: "2026-07-12" },
      { id: "d2", name: "Bank statement — Q2 2026", type: "bank_statement", status: "verified", note: "Consistent history.", uploadedAt: "2026-07-12" },
      { id: "d3", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-12" },
      { id: "d4", name: "Employment letter", type: "employment_letter", status: "verified", note: "Confirmed by district HR.", uploadedAt: "2026-07-12" },
    ],
    creditMemo: {
      summary: "Exceptionally low-risk file. Long public-sector tenure, low leverage, and clean documentation across the board.",
      strengths: ["9-year tenure", "21% DTI", "Clean payment history"],
      concerns: [],
      recommendation: "approve",
      generatedAt: "2026-07-12T11:33:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-12T11:15:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-12T11:15:12Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-12T11:25:00Z", actor: "agent", label: "Running risk model...", detail: "Score computed: 15 / low band" },
      { id: "a4", timestamp: "2026-07-12T11:33:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a5", timestamp: "2026-07-12T11:33:05Z", actor: "system", label: "Ready for officer review." },
      { id: "a6", timestamp: "2026-07-12T13:10:00Z", actor: "officer", label: "Decision recorded: Approved", detail: "By D. Kowalski" },
    ],
    officerDecision: { decidedBy: "D. Kowalski", decision: "approved", note: "Model applicant.", decidedAt: "2026-07-12T13:10:00Z" },
  },
  {
    id: "APP-1049",
    name: "Oliver Standt",
    avatarInitials: "OS",
    loanAmount: 63000,
    loanPurpose: "Debt consolidation",
    submittedAt: "2026-07-13T08:45:00Z",
    status: "rejected",
    employment: { employer: "Standt Retail Group", title: "Store Manager", yearsEmployed: 1, monthlyIncome: 3900, verified: true },
    riskScore: {
      score: 74,
      band: "high",
      debtToIncome: 0.55,
      factors: [
        { label: "High debt-to-income ratio", weight: 0.4, detail: "55% DTI." },
        { label: "Recent delinquency", weight: 0.3, detail: "Two late payments in past 6 months." },
        { label: "Short tenure", weight: 0.15, detail: "1 year at current employer." },
      ],
    },
    documents: [
      { id: "d1", name: "Pay stub — June 2026", type: "pay_stub", status: "verified", note: "Matches declared income.", uploadedAt: "2026-07-13" },
      { id: "d2", name: "Bank statement — Q2 2026", type: "bank_statement", status: "flagged", note: "Two overdraft events in trailing 90 days.", uploadedAt: "2026-07-13" },
      { id: "d3", name: "Government ID", type: "id", status: "verified", note: "Identity confirmed.", uploadedAt: "2026-07-13" },
    ],
    creditMemo: {
      summary: "Debt obligations relative to income exceed policy thresholds, compounded by recent delinquency and overdraft activity.",
      strengths: ["Verified stable employment"],
      concerns: ["55% debt-to-income ratio", "Two late payments in past 6 months", "Recent overdraft activity"],
      recommendation: "reject",
      generatedAt: "2026-07-13T09:05:00Z",
    },
    auditTrail: [
      { id: "a1", timestamp: "2026-07-13T08:45:00Z", actor: "officer", label: "Applicant intake submitted" },
      { id: "a2", timestamp: "2026-07-13T08:45:18Z", actor: "agent", label: "Loading applicant..." },
      { id: "a3", timestamp: "2026-07-13T08:55:00Z", actor: "agent", label: "Calculating debt-to-income ratio...", detail: "55% DTI" },
      { id: "a4", timestamp: "2026-07-13T09:05:00Z", actor: "agent", label: "Generating credit memo..." },
      { id: "a5", timestamp: "2026-07-13T09:05:06Z", actor: "system", label: "Ready for officer review." },
      { id: "a6", timestamp: "2026-07-13T10:40:00Z", actor: "officer", label: "Decision recorded: Rejected", detail: "By S. Alaba" },
    ],
    officerDecision: { decidedBy: "S. Alaba", decision: "rejected", note: "Exceeds DTI policy limit with recent delinquency.", decidedAt: "2026-07-13T10:40:00Z" },
  },
];

export function getApplicantById(id: string): Applicant | undefined {
  return applicants.find((a) => a.id === id);
}

export const impactStats = [
  { label: "Underwriting time", value: "45 min → 8 sec" },
  { label: "Document verification automated", value: "95%" },
  { label: "Pipeline stages automated", value: "3" },
  { label: "Faster loan review", value: "8×" },
];
